version: '3.2'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - './nginx/nginx_error.log:/etc/logs/nginx/nginx_error.log'
      - './nginx/nginx_access.log:/etc/logs/nginx/nginx_access.log'
      - './public:/var/www/html/'
    depends_on:
      - php
  php:
    build: ./php
    volumes:
      - './public:/var/www/html/'
